---
# tasks file for tomcat-war-deploy
- name: Test URL status from local machine
  uri:
    url: "http://servera.example.com:8080"
    status_code: 200
    register: url_status
    delegate_to: localhost

- name: Display URL status
  debug: 
    msg: "Pre-check URL loading fine"
  when: url_status.status == 200

- name: Stop the tomcat service
  service:
    name: tomcat 
    state: stopped
  when: url_status.status == 200

- name: Backup the previous version of the WAR files to /tmp directory
  copy:
    src: /opt/tomcat9/webapps/admin.war
    dest: /tmp/admin.war
    remote_src: yes

- name: Remove the previous version of the WAR and expanded directory
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/tomcat9/webapps/admin.war
    - /opt/tomcat9/webapps/admin
    
- name: Verify the previous contents are gone
  command: "ls -al /opt/tomcat9/webapps/"
  register: list_status

- name: Display list
  debug:
    var: list_status.stdout_lines

    #- name: Download new deployment file
    #  get_url:
    #    url: http://localhost/admin.war
    #   dest: /opt/tomcat9/webapps/admin.war

- name: copy file to dest
  copy:
    src: /home/mdtahmeed/Documents/Ansible-tomcat-war-deploy/admin.war
    dest: /opt/tomcat9/webapps/admin.war

- name: set file permissions
  file: 
    path: /opt/tomcat9/webapps/admin.war
    mode: 0660
    owner: tomcat 
    group: tomcat
      #notify: start tomcat

- name: start tomcat service
  service:
    name: tomcat
    state: started

- name: wait for 20 second for URL to load
  wait_for:
    timeout: 20
    
- name: Verify war is deployed
  command: "ls -al /opt/tomcat9/webapps/"
  register: list_status

- name: Display list
  debug:
    var: list_status.stdout_lines


- name: Get URL status
  uri:  
    url: "http://servera.example.com:8080/admin/"
    return_content: yes
    status_code: 200
  register: deployment_status
  delegate_to: localhost

- name: Display deployment status
  debug:
    msg: "WAR file Deployment successfully on servera.example.com"
  when: deployment_status.status == 200